# Generated by Django 4.1.3 on 2022-11-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protineproduct',
            name='product_img',
            field=models.ImageField(default=None, null=True, upload_to='products'),
        ),
    ]
